### 1. Creación de arreglos

In [1]:
import numpy as np

# Crea un arreglo de 10 elementos con números aleatorios entre 1 y 100
arr_random = np.random.randint(1, 101, size=10)
print("Arreglo de números aleatorios:", arr_random)

Arreglo de números aleatorios: [92 71 53 13 66 83 18 70 26 82]


### 2. Operaciones básicas

In [3]:
arr = np.array([1, 2, 3, 4, 5])

# Suma todos los elementos
suma = np.sum(arr)

# Resta 2 a cada elemento
resta = arr - 2

# Multiplica cada elemento por 3
multiplicacion = arr * 3

print("Suma:", suma)
print("Resta 2:", resta)
print("Multiplica por 3:", multiplicacion)

Suma: 15
Resta 2: [-1  0  1  2  3]
Multiplica por 3: [ 3  6  9 12 15]


### 3. Indexación y slicing

In [4]:
arr_slice = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Primeros 3 elementos
primerosTres = arr_slice[:3]

# Últimos 2 elementos
ultimosDos = arr_slice[-2:]

# Elementos en las posiciones 2, 4 y 6
posiciones = arr_slice[[2, 4, 6]]

print("Primeros 3 elementos:", primerosTres)
print("Últimos 2 elementos:", ultimosDos)
print("Elementos en posiciones 2, 4 y 6:", posiciones)

Primeros 3 elementos: [1 2 3]
Últimos 2 elementos: [8 9]
Elementos en posiciones 2, 4 y 6: [3 5 7]


### 4. Reshaping

In [6]:
arr_reshape = np.arange(12)

# Redimensionalo para que tenga forma (3, 4)
reshaped = arr_reshape.reshape(3, 4)

print("Arreglo redimensionado (3, 4):\n", reshaped)

Arreglo redimensionado (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


###  5. Arreglos multidimensionales

In [11]:
# Crea un arreglo de 2 dimensiones con forma (3, 3)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Suma de cada fila
sumaFilas = np.sum(arr_2d, axis=1)

print("Suma de cada fila:", sumaFilas)

Suma de cada fila: [ 6 15 24]


### 6. Funciones matemáticas

In [20]:
arr_math = np.array([1, 2, 3, 4, 5])

# Media aritmética
mediaAritmetica = np.mean(arr_math)

# Mediana
mediana = np.median(arr_math)

# Desviación estándar
desviacionEstandar = np.std(arr_math)

print("Media:", mediaAritmetica)
print("Mediana:", mediana)
print("Desviación estándar:", desviacionEstandar)


Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951


### 7. Comparaciones

In [21]:
arr_comp = np.array([1, 2, 3, 4, 5])

# Elementos que son mayores que 3
mayoresQueTres = arr_comp[arr_comp > 3]

print("Elementos mayores que 3:", mayoresQueTres)


Elementos mayores que 3: [4 5]


### 8. Concatenación

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenación
concatenated = np.concatenate((arr1, arr2))

print("Arreglo concatenado:", concatenated)


Arreglo concatenado: [1 2 3 4 5 6]


### 9. Arreglos booleanos

In [26]:
# Crea un arreglo booleano de 5 elementos
bool_arr = np.array([True, False, True, False, True])

# Selecciona los elementos que son True
elementosVerdaderos = bool_arr[bool_arr]

print("Elementos que son True:", elementosVerdaderos)

Elementos que son True: [ True  True  True]


### 10. Funciones de agregación

In [27]:
arr_agg = np.array([1, 2, 3, 4, 5])

# Suma acumulada
cumulative_sum = np.cumsum(arr_agg)

print("Suma acumulada:", cumulative_sum)

Suma acumulada: [ 1  3  6 10 15]


### 11. Suma de vectores

In [28]:
# Vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma vectorial
vector_sum = a + b

print("Suma de vectores:", vector_sum)


Suma de vectores: [5 7 9]


### 12. Producto escalar 

In [29]:
# Producto escalar
productoEscalar = np.dot(a, b)

print("Producto escalar:", productoEscalar)

Producto escalar: 32


### 13. Producto vectorial

In [31]:
# Producto vectorial
productoVectorial = np.cross(a, b)

print("Producto vectorial:", productoVectorial)

Producto vectorial: [-3  6 -3]


### 14. Magnitud de un vector

In [32]:
vector_a = np.array([3, 4])

# Magnitud
magnitud = np.linalg.norm(vector_a)

print("Magnitud de a:", magnitud)

Magnitud de a: 5.0


### 15. Normalización de un vector

In [33]:
# Normalización
normalized_vector = vector_a / magnitud

print("Vector normalizado:", normalized_vector)

Vector normalizado: [0.6 0.8]


### 16.  Distancia entre vectores

In [34]:
# Distancia entre vectores
distance = np.linalg.norm(a - b)

print("Distancia entre a y b:", distance)

Distancia entre a y b: 5.196152422706632


### 17. Ángulo entre vectores


In [36]:
# Cálculo del ángulo en radianes
coseno = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
radian = np.arccos(coseno)

# Convertir a grados
anguloGrados = np.degrees(radian)

print("Ángulo entre a y b (grados):", anguloGrados)

Ángulo entre a y b (grados): 12.933154491899135


### 18. Proyección de un vector sobre otro

In [37]:
# Proyección de a sobre b
proyeccion = (np.dot(a, b) / np.dot(b, b)) * b

print("Proyección de a sobre b:", proyeccion)

Proyección de a sobre b: [1.66233766 2.07792208 2.49350649]


### 19. Vector unitario


In [38]:
# Vector unitario
vectorUnitario = vector_a / np.linalg.norm(vector_a)

print("Vector unitario de a:", vectorUnitario)


Vector unitario de a: [0.6 0.8]


### 20. Rotación de un vector

In [39]:
# Rotación de un vector 90 grados en sentido contrario a las agujas del reloj
theta = np.radians(90)  
rotacion = np.array([[np.cos(theta), -np.sin(theta)], 
                             [np.sin(theta), np.cos(theta)]])

vectorRotado = rotacion @ vector_a

print("Vector rotado 90 grados:", vectorRotado)

Vector rotado 90 grados: [-4.  3.]
